# Generated by Django 5.0.2 on 2024-02-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombreUsuario', models.CharField(max_length=50)),
                ('telefonoUsuario', models.CharField(max_length=10)),
                ('emailUsuario', models.EmailField(max_length=254, unique=True)),
                ('direccionUsuario', models.CharField(max_length=15)),
            ],
        ),
    ]
