# Generated by Django 5.0.2 on 2024-02-28 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PerfilApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoriaEgreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCategoriaEgreso', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='categoriaIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCategoriaIngreso', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='egresos',
            fields=[
                ('idEgreso', models.AutoField(primary_key=True, serialize=False)),
                ('montoEgreso', models.IntegerField()),
                ('fechaEgreso', models.DateField()),
                ('descripcionEgreso', models.TextField()),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PerfilApp.usuario')),
                ('nombreCategoriaEgreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicioApp.categoriaegreso')),
            ],
        ),
        migrations.CreateModel(
            name='ingreso',
            fields=[
                ('idIngreso', models.AutoField(primary_key=True, serialize=False)),
                ('nombreIngreso', models.CharField(max_length=50)),
                ('montoIngreso', models.IntegerField()),
                ('fechaIngreso', models.DateField()),
                ('descripcionIngreso', models.TextField()),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PerfilApp.usuario')),
                ('nombreCategoriaIngreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicioApp.categoriaingreso')),
            ],
        ),
    ]
